# Generated by Django 2.2.1 on 2019-05-21 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20190521_0553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Предприятие',
                'verbose_name_plural': 'Предприятия',
            },
        ),
        migrations.RenameModel(
            old_name='EnterprisesGroup',
            new_name='CompanyGroup',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.Category')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Product')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='company_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.CompanyGroup'),
        ),
        migrations.AddField(
            model_name='company',
            name='districts',
            field=models.ManyToManyField(to='mainapp.District'),
        ),
    ]
