# Generated by Django 2.2.1 on 2019-05-21 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20190521_0656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name': 'Цена', 'verbose_name_plural': 'Цены'},
        ),
        migrations.AlterField(
            model_name='company',
            name='company_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.CompanyGroup', verbose_name='Группа компаний'),
        ),
        migrations.AlterField(
            model_name='company',
            name='districts',
            field=models.ManyToManyField(to='mainapp.District', verbose_name='Районы'),
        ),
        migrations.AlterField(
            model_name='price',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Company', verbose_name='Предприятие'),
        ),
        migrations.AlterField(
            model_name='price',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.Category', verbose_name='Категория'),
        ),
    ]
